--------------------------------
--Magnitude Analysis
--------------------------------

--Finding the total customers by country
	SELECT country, COUNT(*) cust_count FROM gold.dim_customers
	GROUP BY country
	ORDER BY COUNT(*) DESC

--Finding the total customers by gender
	SELECT gender, COUNT(*) cust_count FROM gold.dim_customers
	GROUP BY gender
	ORDER BY COUNT(*) DESC

--Finding the total products by category
	SELECT category, count(*) prod_count FROM gold.dim_products
	GROUP BY category
	ORDER BY count(*) DESC

--What is the average cost of each category
	SELECT category, AVG(cost) avg_cost FROM gold.dim_products
	GROUP BY category
	ORDER BY AVG(cost) DESC

--What is the  revenue generated by each category
	SELECT p.category, SUM(fs.sales) as rev_generated  FROM gold.fact_sales fs
	LEFT JOIN gold.dim_products p ON p.product_key = fs.product_key
	GROUP BY p.category
	ORDER BY SUM(fs.sales) DESC
	

--Finding total revenue generated by each customer
	SELECT c.primary_key, c.first_name, c.last_name, SUM(sales) as rev_generated FROM gold.fact_sales fs
	LEFT JOIN gold.dim_customers c ON c.primary_key = fs.customer_key
	GROUP BY c.primary_key, c.first_name, c.last_name
	ORDER BY SUM(sales) DESC

--What is the distribution of sold items across countries 
	SELECT c.country, COUNT(fs.quantity) as distribution FROM gold.fact_sales fs
	LEFT JOIN gold.dim_customers c ON c.primary_key = fs.customer_key
	GROUP BY c.country
	ORDER BY COUNT(fs.quantity) DESC
